version: "3.8"

services:
  postgress:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: smit5525
      POSTGRES_PASSWORD: smit123456
      POSTGRES_DB: school
    ports:
      - "5525:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://smit5525:smit123456@localhost:5525/school
    depends_on:
      - postgres

volumes:
  postgres_data:
